spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rkdguschlrhear@gmail.com          # ✅ 너의 이메일
    password: eizzrczwqhljszgs                  # ✅ 앱 비밀번호 (16자리)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    secret: AQC7KfGZ2L8q3P9sV4yT8uX0aB5dE6gH7jK9mN2pQ=
    expiration-ms: 86400000  

  datasource:
    url: jdbc:postgresql://dpg-d07hffc9c44c739vphvg-a.singapore-postgres.render.com:5432/judebalance  # ✅ Render 주소로 변경
    username: postgres1234                # ✅ Render 제공 username
    password: 7jbJlaWZZdbTfPMzpSBsUv97uJ5wyqwJ  # ✅ Render 제공 password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
